### ISSUE TITLE
Criar Visualização Básica dos Dados

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#154]
## Descrição

Eu, como usuário, gostaria de visualizar os dados especificados nas buscas, para que eu possa fazer uso deles.

## Tipo

- História de Usuário

## Tasks
- Fazer download dos dados
- Visualização de tabela

## Critérios de aceitação

- [x] Visualizar dados em tabela
- [x] Consumir dados a partir de um dado no formato json
- [x] Segui protótipo de alta fidelidade
- [x] Fazer download dos dados por meio de arquivo csv
