### ISSUE TITLE
Realizar Busca por meio de Agrupamentos

### ISSUE THREAD

**Issue by Joranhezon** [fga-eps-mds/2018.2-GrupoMDIC#158]
## Descrição

Eu, como usuário, gostaria de poder realizar uma busca avançada por meio de agrupamentos, de maneira que minha busca seja mais efetiva.

## Tipo

- História de Usuário

## Tasks
- Criar Requisição do Front para o Back
- Refinar o filtro de agrupamento

## Critérios de aceitação

- [x] Realizar requisição do Front para o Back
- [x] Realizar Integração de dados do Front para Requisição
- [x] Receber dados referentes a busca do back

**Comment by rogerioo** [comment]
Foram realizadas diversas pesquisas, com diferentes propostas de solução, sobre o assunto desde a sprint 9 até o presente momento (sprint 10), todavia não achamos documentado nada que possa solucionar o problema com o GraphQl na API. Pode ser que tenha como tratar os dados para serem agrupados no FrontEnd.

Realizaram as pesquisas @rogerioo , @MarcosNBJ, @joao15victor08  e o @andrelucasf .

**Comment by rogerioo** [comment]
Retificando o último comentário, foi encontrado uma forma de dar o join nas models que permitiu o agrupamento de dados relacionados por 'icontains'.

**Comment by MarcosNBJ** [comment]
Pull Request feito no repositório do FrontEnd com as funcionalidades que cumprem o pedido na issue.

**Comment by Joranhezon** [comment]
Ok! Darei uma olhada agora.

**Comment by Joranhezon** [comment]
Aceitei o [PR](https://github.com/fga-eps-mds/2018.2-ComexStat-FrontEnd/pull/14) e fecharei a issue.
